#!/usr/bin/with-contenv bash
# vim: ft=bash
# shellcheck shell=bash
#==============================================================================
# OpenThread BorderRouter web interface finish script
#==============================================================================
echo "INFO: otbr-web ended with exit code ${1} (signal ${2})..."
