name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@d3f92d051b409116f0c3e878ee69f482dd6dcdd7 # 2.0.55
    with:
      image-name: homeassistant-otbr
      create-artifacts: false
      arm64-build-args: |
        ARCH=aarch64
