name: publish-image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@6d890b5b6e2828cfa8c4006113fb62609802d9bd # 2.0.32
    permissions:
      contents: read
      packages: write
    with:
      image-name: homeassistant-otbr
      registries: |
        docker.io
        ghcr.io
      registry-namespaces: |
        denniswitt
        wittdennis
      arm64-build-args: |
        ARCH=aarch64
    secrets:
      registry-passwords: |
        ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        ${{ secrets.GITHUB_TOKEN }}
