name: publish-image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@7a91e18ddb5919549340a582dda28244b5de3c48 # 2.0.28
    permissions:
      contents: read
      packages: write
    with:
      image-name: homeassistant-otbr
      registries: |
        docker.io
        ghcr.io
      registry-namespaces: |
        denniswitt
        wittdennis
      arm64-build-args: |
        ARCH=aarch64
    secrets:
      registry-passwords: |
        ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        ${{ secrets.GITHUB_TOKEN }}
