name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: "The version for the release. Use auto for conventional commit auto calculation"
        required: true

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@6d890b5b6e2828cfa8c4006113fb62609802d9bd # 2.0.32
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
