name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: "The version for the release. Use auto for conventional commit auto calculation"
        required: true

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@074d25eb9a24f5ccd89dd2ef96fd1826107895f9 # 2.0.43
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
