name: github-release

on:
  workflow_dispatch:
    inputs:
      version:
        default: "auto"
        description: "The version for the release. Use auto for conventional commit auto calculation"
        required: true

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@749bb65f519a91aab3502c33024e62051793edda # 2.0.46
    with:
      version: ${{ inputs.version }}
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
